[package]
name = "engine"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
async-std = "1.12.0"
chess = "3.2.0"
futures = "0.3.24"
vampirc-uci = {version = "0.11", features = ["chess"]}